version: '3'

tasks:
  install:
    desc: Install dependencies
    cmds:
      - bun install

  generate:
    desc: Generate a test set of mazes
    cmds:
      - bun run src/cli/index.ts generate {{.CLI_ARGS}}

  import:
    desc: Import mazes from JSON files in input/ directory
    cmds:
      - bun run src/cli/index.ts import {{.CLI_ARGS}}

  evaluate:
    desc: Run model evaluation on a test set
    cmds:
      - bun --env-file=.env run src/cli/index.ts evaluate {{.CLI_ARGS}}

  evaluate-manual:
    desc: Evaluate manual solutions against a test set
    cmds:
      - bun run src/cli/index.ts evaluate-manual {{.CLI_ARGS}}

  score:
    desc: Compute LMIQ scores from evaluation results
    cmds:
      - bun run src/cli/index.ts score {{.CLI_ARGS}}

  baseline:
    desc: Set custom human baselines for a test set
    cmds:
      - bun run src/cli/index.ts set-baseline {{.CLI_ARGS}}

  prompt-demo:
    desc: Generate a prompt for inspection
    cmds:
      - bun run src/cli/index.ts prompt-demo {{.CLI_ARGS}}

  export:
    desc: Export evaluation results to JSON for the UI
    cmds:
      - bun run src/cli/index.ts export {{.CLI_ARGS}}

  delete:
    desc: Delete evaluation runs from the database
    cmds:
      - bun run src/cli/index.ts delete {{.CLI_ARGS}}

  retry:
    desc: Retry failed evaluations from a previous run
    cmds:
      - bun --env-file=.env run src/cli/index.ts retry {{.CLI_ARGS}}

  ui:
    desc: Start the server and both UI apps (human eval on 5173, visualizer on 5174)
    cmds:
      - bun run src/server/index.ts & bunx --bun vite --config src/ui/vite.config.ts & bunx --bun vite --config src/ui-visualizer/vite.config.ts

  format:
    desc: Format code with Biome
    cmds:
      - bunx biome format --write .

  lint:
    desc: Lint code with Biome
    cmds:
      - bunx biome lint .

  check:
    desc: Run all checks (format + lint + typecheck)
    cmds:
      - bunx biome check .
      - bunx tsc --noEmit

  tsc:
    desc: Run TypeScript type checking
    cmds:
      - bunx tsc --noEmit

  studio:
    desc: Open Drizzle Studio to inspect the database
    cmds:
      - bunx drizzle-kit studio

  backup:
    desc: Backup the evaluation database
    cmds:
      - cp results/eval.db "results/eval-$(date +%Y%m%d-%H%M%S).db"
      - echo "Backup created"
